algoritmo "Analizador de Strings"
// Função :
// Autor :
// Data : 26/01/2023
// Seção de Declarações 
var
n: caractere
inicio
// Seção de Comandos 

escreval("Digite um nome")
leia (n)
Escreval("Total de letras em seu nome: ",compr(n))
Escreval("seu nome em maiusculas: ",maiusc(n))
Escreval("seu nome em minusculas: ",minusc(n))
Escreval("A primeira letra do seu nome: ",copia(n,1,1))
fimalgoritmo
