algoritmo "somador numerico"
// Função :
// Autor :
// Data : 11/03/2022
// Seção de Declarações
var
contador, valor, salto: Inteiro
inicio
// Seção de Comandos
contador  <- 0
Escreva ("Até quanto vc quer contar? ")
leia (valor)
Escreva ("Qual intervalo quer contar? ")
leia (salto)
enquanto (contador <= valor) faca
   Escreval (contador)
   contador <- contador + salto
fimenquanto
Escreval ("Terminei de contar")
fimalgoritmo
