algoritmo "semnome"
// Função :
// Autor :
// Data : 11/03/2022
// Seção de Declarações 
var
    contador, valor, intervalo: Inteiro
inicio
// Seção de Comandos
   contador <- 0
   escreva ("quer contar até quanto? ")
   leia (valor)
   escreva ("Qual será o intervalor ? ")
   leia (intervalo)
   enquanto (contador <= valor) faca
       Escreval (contador)
       contador <- contador + intervalo
   fimenquanto
   Escreval ("Terminei de contar")
fimalgoritmo
