algoritmo "semnome"
// Função :
// Autor :
// Data : 10/03/2022
// Seção de Declarações 
var
Nome, mes: caractere
salario: Real
inicio
// Seção de Comandos
escreval ("Olá qual o nome do funcionario? Digite ao lado: ")
leia (nome)
escreval ("Olá qual salário? Digite ao lado: ")
leia (salario)
escreval ("Olá qual o mes em questao? Digite ao lado: ")
leia (mes)
escreva ("Olá o fucionário(a) ", nome, " tem um salario de R$", salario, ", no mes de ", mes," obrigado pela consulta!")
fimalgoritmo
