algoritmo "exercicio encontrar o delta "
// Função :
// Autor :
// Data : 10/03/2022
// Seção de Declarações 
var
   a, b, c, delta : Real

inicio
escreva ("Qual o valor de A? :")
leia (a)
escreva ("Qual valor de B? :")
leia (b)
escreva ("Qual valor de C? :")
leia (c)
delta <-  b^2-4*(a * c))
escreval ("considerando que A: ", a," e B: ",b, " e C: ",c, " então o Delta é: ", delta )



// Seção de Comandos 
fimalgoritmo
